### ISSUE TITLE
Definir un formato de idioma.

### ISSUE THREAD

**Issue by penserbjorne** [LIDSOL/nightlynight#2]
### Se necesita crear ###
- [ ] Video Nuevo
- [ ] Entrada en el blog
- [ ] Videocharla
- [x] Otros:  
> Describe Otros: Definir un formato de idioma.

### Para tratar ###
- [ ] Comunidad
- [ ] Tema Nuevo
- [ ] Evento
- [ ] Nueva Versión de FX
- [ ] Offtopic
- [x] Otros
> Describe Otros: Documentación en el repo y en el proyecto.

### Objetivo ###
Definir un formato de idioma para manejar la documentación en el repo y en el proyecto.

### Actividades Propuestas ###
- Definir la estructura de idioma que se usara en la documentación, ¿español? ¿ingles? ¿espanglish?

### Donde se llevará a cabo ###
- [ ] Canal de YouTube
- [ ] Blog
- [x] Grupo de Telegram , indicando el resultado en este issue
- [ ] Mumble

### Corresponsables (si los hay) ###
> @lasr21 
> @siclemx 

### Documentación y Enlaces Relacionados ###
* [Nombre de Enlace](https://Enlace "Nombre de Enlace")

**Comment by siclemx** [comment]
Hola, tras hablar al respecto en el grupo de Telegram se definio que se trabajara sobre Español para el proyecto y la documentación en general, sin embargo, si alguien gusta empezar a trabajar en la traduccion al inglés es bien recibido, aclarando que por ahora toda comunicación es en Español.

Igualmente se trabajará en corregir las partes de la documentación que se encuentren en Inglés y ajustarnos a lo decidido por todos.
